// Remaining FDC entries 101-338
export const FDC_REMAINING_ENTRIES = [
  { id: 101, combination: "Cilnidipine + Metoprolol Succinate + Metoprolol Tartrate" },
  { id: 102, combination: "Ciprofloxacin + Fluocinolone + Clotrimazole + Neomycin + Chlorocresol" },
  { id: 103, combination: "Ciprofloxacin + Fluticasone + Clotrimazole + Neomycin" },
  { id: 104, combination: "Ciprofloxacin + Phenazopyridine" },
  { id: 105, combination: "Clidinium + Paracetamol + Dicyclomine + Activated Dimethicone" },
  { id: 106, combination: "Clindamycin + Clotrimazole + Lactic Acid Bacillus" },
  { id: 107, combination: "Clindamycin + Telmisartan" },
  { id: 108, combination: "Clobetasol + Gentamicin + Tolnaftate + lodochlorhydroxyquinone + Ketoconazole" },
  { id: 109, combination: "Clobetasol + Neomycin + Miconazole + Clotrimazole" },
  { id: 110, combination: "Clobetasol + Neomycin + Miconazole + Zinc Sulphate" },
  { id: 111, combination: "Clobetasol + Ofloxacin + Ketoconazol + Zinc Sulphate" },
  { id: 112, combination: "Clobetasol + Ofloxacin + Miconazole + Zinc Sulphate" },
  { id: 113, combination: "Clobetasol Propionate + Ofloxacin + Ornidazole + Terbinafine" },
  { id: 114, combination: "Clobetasole + Gentamicin + Miconazole + Zinc Sulphate" },
  { id: 115, combination: "Clomifene Citrate + Ubidecarenone + Zinc + Folic Acid + Methylcobalamin + Pyridoxine + Lycopene + Selenium + Levocarnitine Tartrate + L-Arginine" },
  { id: 116, combination: "Clotrimazole + Beclomethasone + Lignocaine + Ofloxacin + Acetic Aicd + Sodium Methyl Paraben +Propyl Paraben" },
  { id: 117, combination: "Clotrimazole + Beclomethasone + Ofloxacin + Lignocaine" },
  { id: 118, combination: "Clotrimazole + Ofloxaxin + Lignocaine + Glycerine and Propylene Glycol" },
  { id: 119, combination: "Codeine + Chlorpheniramine + Alcohol Syrup" },
  { id: 120, combination: "Codeine + Levocetirizine + Menthol" },
  { id: 121, combination: "Combikit of 3 tablets of Serratiopeptidase (enteric coated 20000 units) + Diclofenac Potassium & 2 tablets of D" },
  { id: 122, combination: "Combikit of Azithromycin, Secnidazole and Fluconazole" },
  { id: 123, combination: "Combikit of Fluconazole Tablet, Azithromycin Tablet and Ornidazole Tablets" },
  { id: 124, combination: "Cyproheptadine + Thiamine" },
  { id: 125, combination: "Dextrometharphan + Chlopheniramine + Ammonium Chloride+ Menthol" },
  { id: 126, combination: "Dextrometharphan + Chlopheniramine + Ammonium + Sodium Citrate + Menthol" },
  { id: 127, combination: "Dextrometharphan + Phenylephrine + Guaiphenesin" },
  { id: 128, combination: "Dextromethophan + Chlopheniramine + Bromhexine" },
  { id: 129, combination: "Dextromethorphan + Ambroxol + Ammonium Chloride + Chlorpheniramine + Menthol" },
  { id: 130, combination: "Dextromethorphan + Ambroxol + Guaifenesin + Phenylephrine + Chlorpheniramine" },
  { id: 131, combination: "Dextromethorphan + Bromhexine + Guaiphenesin" },
  { id: 132, combination: "Dextromethorphan + Bromhexine + Guaiphenesin + Menthol" },
  { id: 133, combination: "Dextromethorphan + Cetirizine" },
  { id: 134, combination: "Dextromethorphan + Cetirizine + Guaifenesin + Ammonium Chloride" },
  { id: 135, combination: "Dextromethorphan + Chlorpheniramine + Chlorpheniramine Maleate" },
  { id: 136, combination: "Dextromethorphan + Chlorpheniramine + Guaiphenesin" },
  { id: 137, combination: "Dextromethorphan + Levocetirizine + Phenylephrine + Zinc" },
  { id: 138, combination: "Dextromethorphan + Paracetamol + Cetirizine + Phenylephrine" },
  { id: 139, combination: "Dextromethorphan + Phenylephrine + Ammonium Chloride + Menthol" },
  { id: 140, combination: "Dextromethorphan + Phenylephrine + Bromhexine + Guaifenesin + Chlorpheniramine" },
  { id: 141, combination: "Dextromethorphan + Phenylephrine + Cetirizine + Paracetamol + Caffeine" },
  { id: 142, combination: "Dextromethorphan + Phenylephrine + Cetirizine + Zinc + Menthol" },
  { id: 143, combination: "Dextromethorphan + Phenylephrine + Guaifenesin + Certirizine + Acetaminophen" },
  { id: 144, combination: "Dextromethorphan + Phenylephrine + Guaifenesin + Triprolidine" },
  { id: 145, combination: "Dextromethorphan + Phenylephrine + Tripolidine + Menthol" },
  { id: 146, combination: "Dextromethorphan + Phenylephrine + Zinc Gluconate + Menthol" },
  { id: 147, combination: "Dextromethorphan + Tripolidine + Phenylephirine" },
  { id: 148, combination: "Dextromethorphan + Triprolidine + Phenylephrine" },
  { id: 149, combination: "Dextromethorphen + Bromhexine + Chlorpheniramine Maleate + Guaiphenesin" },
  { id: 150, combination: "Dextromethorphen + Promethazine" },
  { id: 151, combination: "Diclofenac + paracetamol + chlorpheniramine maleate + mgnesium Trisillicate" },
  { id: 152, combination: "Diclofenac + Paracetamol + Chlorzoxazone + Famotidine" },
  { id: 153, combination: "Diclofenac + paracetamol + magnesium Trisilicate" },
  { id: 154, combination: "Diclofenac + Paracetamol injection" },
  { id: 155, combination: "Diclofenac + Tramadol + Chlorzoxazone" },
  { id: 156, combination: "Diclofenac + Tramadol + Paracetamol" },
  { id: 157, combination: "Diclofenac + Zinc Carnosine" },
  { id: 158, combination: "Dicyclomine + Paracetamol + Domperidone" },
  { id: 159, combination: "Diethyl Carbamazine + Chlorpheniramine + Guaifenesin" },
  { id: 160, combination: "Diethylcabamazine Citrate + Cetirizine + Guaiphenesin" },
  { id: 161, combination: "Diethylcarbamazine + Cetirizine + Ambroxol" },
  { id: 162, combination: "Diphenhydramine + Guaifenesin + Bromhexine + Ammonium Chloride + Menthol" },
  { id: 163, combination: "Diphenhydramine + Guaiphenesin + Ammonium Chloride + Bromhexine" },
  { id: 164, combination: "Diphenhydramine + Terpine + Ammonium Chloride + Sodium Chloride + Menthol" },
  { id: 165, combination: "Diphenoxylate + Atropine + Furazolidonee" },
  { id: 166, combination: "Disodium Hydrogen Citrate + Paracetamol" },
  { id: 167, combination: "Doxycycline + Serratiopeptidase" },
  { id: 168, combination: "Doxylamine + Pyridoxine + Mefenamic Acid + Paracetamol" },
  { id: 169, combination: "Dried Alumnium Hydroxie Gel + Prophantheline + Diazepam" },
  { id: 170, combination: "Drotaverine + Clidinium + Chlordiazepoxide" },
  { id: 171, combination: "Enrofloxacin + Bromhexin" },
  { id: 172, combination: "Ergotamine Tartrate + Belladona Dry Extarct+Caffeine + Paracetamol" },
  { id: 173, combination: "Ethylmorphine + Noscapine + Chlorpheniramine" },
  { id: 174, combination: "Famotidine + Oxytacaine + Magaldrate" },
  { id: 175, combination: "Flunarizine + Paracetamole + Domperidone" },
  { id: 176, combination: "Flupentixol + Escitalopram" },
  { id: 177, combination: "Furazolidone + Metronidazole + Loperamide" },
  { id: 178, combination: "Gabapentin + Mecobalamin + Pyridoxine + Thiamine" },
  { id: 179, combination: "Gentamicin Sulphate + Clotrimazole + Betamethasone + Lignocaine" },
  { id: 180, combination: "Gentamycin + Dexamethasone + Chloramphenicol + Tobramycin + Ofloxacin" },
  { id: 181, combination: "Glibenclamide + Metformin (SR)+ Pioglitazone" },
  { id: 182, combination: "Gliclazide 40mg + Metformin 400mg" },
  { id: 183, combination: "Gliclazide 80 mg + Metformin 325 mg" },
  { id: 184, combination: "Glimepiride + Pioglitazone + Metformin" },
  { id: 185, combination: "Glimepiride 1mg/2mg/3mg + Pioglitazone 15mg/15mg/15mg + Metformin 1000mg/1000mg/1000mg" },
  { id: 186, combination: "Glimepiride 1mg/2mg+ Pioglitazone 15mg/15mg + Metformin 850mg/850mg" },
  { id: 187, combination: "Glipizide 2.5mg + Metformin 400 mg" },
  { id: 188, combination: "Glucosamine + Methyl Sullfonyl Methane + Vitamin D3 + Manganese + Boron + Copper + Zinc" },
  { id: 189, combination: "Guaifenesin + Bromhexine + Chlorpheniramine + Paracetamol" },
  { id: 190, combination: "Guaifenesin + Bromhexine + Chlorpheniramine + Phenylephrine + Paracetamol + Serratiopeptidase(as enteric coated granules) 10000 SP Units" },
  { id: 191, combination: "Guaifenesin + Dextromethorphan" },
  { id: 192, combination: "Guaifenesin + Diphenhydramine + Bromhexine + Phenylephrine" },
  { id: 193, combination: "Heparin + Diclofenac" },
  { id: 194, combination: "Imipramine + Chlordiazepoxide + Trifluoperazine + Trihexyphenidyl" },
  { id: 195, combination: "Ketoconazole + Tea Tree oil + Allantion + Zinc Oxide + Aloe Vera + Jojoba oil + Lavander oil + Soa noodels" },
  { id: 196, combination: "Ketotifen + Cetirizine" },
  { id: 197, combination: "Ketotifen + Levocetrizine" },
  { id: 198, combination: "Ketotifen + Theophylline" },
  { id: 199, combination: "L-5-Methyltetrahydrofolate Calcium + Escitalopram" },
  { id: 200, combination: "L-Arginine + Sildenafil" },
  { id: 201, combination: "Levocetirizine + Ambroxol + Phenylephrine + Guaiphenesin" },
  { id: 202, combination: "Levocetirizine + Ambroxol + Phenylephrine + Paracetamol" },
  { id: 203, combination: "Levocetirizine + Dextromethorphan + Zinc" },
  { id: 204, combination: "Levocetirizine + Montelukast + Acebrophylline" },
  { id: 205, combination: "Levocetirizine + Paracetamol + Phenylephirine + Caffeine" },
  { id: 206, combination: "Levocetirizine + Phenylephrine + Ambroxol + Guaiphenesin + Paracetamol" },
  { id: 207, combination: "Levocetirizine + Ranitidine" },
  { id: 208, combination: "Levofloxacin + Bromhexine" },
  { id: 209, combination: "Levofloxacin + Ornidazole + Alpha Tocopherol Acetate" },
  { id: 210, combination: "Levothyroxine + Phyridoxine + Nicotinamide" },
  { id: 211, combination: "Lignocaine + Clotrimazole + Ofloxacin + Beclomethasone" },
  { id: 212, combination: "Lornoxicam + Paracetamol + serratiopeptidase" },
  { id: 213, combination: "Lornoxicam + paracetamol + Tramadol" },
  { id: 214, combination: "Lornoxicam + paracetamol + trypsin" },
  { id: 215, combination: "Magaldrate + Famotidine + Simethicone" },
  { id: 216, combination: "Magaldrate + Papain + Fungul Diastase + Simethicone" },
  { id: 217, combination: "Magaldrate + Ranitidine + Pancreatin + Domperidone" },
  { id: 218, combination: "Mebeverine & Inner HPMC capsule (Streptococcus Faecalis + Clostridium butyricum + Bacillusmesentricus + Lactic Acid Bacillus)" },
  { id: 219, combination: "Menthol + Anesthetic Ether" },
  { id: 220, combination: "Metformin (SR) 500mg + Pioglitazone 5mg" },
  { id: 221, combination: "Metformin (Sustainded Release) 500mg + Pioglitazone 15 mg + Glimepiride 3mg" },
  { id: 222, combination: "Metformin + Atorvastatin" },
  { id: 223, combination: "Metformin + Bromocriptine" },
  { id: 224, combination: "Metformin + Gliclazide + Chromium Polynicotinate" },
  { id: 225, combination: "Metformin + Gliclazide + Piogllitazone + Chromium Polynicotinate" },
  { id: 226, combination: "Metformin + Glimepiride + Methylcobalamin" },
  { id: 227, combination: "Metformin 1000/1000/500/500mg + Pioglitazone 7.5/7.5/7.5/7.5mg + Glimepiride 1/2/1/2mg" },
  { id: 228, combination: "Metformin 500mg/500mg+Gliclazide SR 30mg/60mg + Pioglitazone 7.5mg/7.5mg" },
  { id: 229, combination: "Metformin 850mg + Pioglitazone 7.5 mg + Glimepiride 1mg" },
  { id: 230, combination: "Metformin 850mg + Pioglitazone 7.5 mg + Glimepiride 2mg" },
  { id: 231, combination: "Metformin ER + Gliclazide MR + Voglibose" },
  { id: 232, combination: "Metronidazole + Norfloxacin" },
  { id: 233, combination: "Metronidazole + Tetracycline" },
  { id: 234, combination: "N-Acetyl Cysteine + Ambroxol + Phenylephrine + Levocertirizine" },
  { id: 235, combination: "Naphazoline + Carboxy Methyl Cellulose + Menthol + Camphor + Phenylephrine" },
  { id: 236, combination: "Naphazoline + Chlorpheniramine + Zinc Sulphate + Boric Acid + Sodium Chloride + Chlorobutol" },
  { id: 237, combination: "Naproxen + Paracetamol" },
  { id: 238, combination: "Neomycin + Doxycycline" },
  { id: 239, combination: "Nimesulide + Certirizine + Phenylephrine" },
  { id: 240, combination: "Nimesulide + Cetrizine + Caffeine" },
  { id: 241, combination: "Nimesulide + Diclofenac" },
  { id: 242, combination: "Nimesulide + Dicyclomine" },
  { id: 243, combination: "Nimesulide + Loratadine + Phenylephrine + Ambroxol" },
  { id: 244, combination: "Nimesulide + Paracetamol + Cetirizine + Phenylephrine" },
  { id: 245, combination: "Nimesulide + Paracetamol + Levocetirizine + Phenylephrine + Caffeine" },
  { id: 246, combination: "Nimesulide + paracetamol Injection" },
  { id: 247, combination: "Nimesulide + Paracetamol Suspension" },
  { id: 248, combination: "Nimesulide + Phenylephrine + Caffeine + Levocetirizine" },
  { id: 249, combination: "Nimesulide + Pitofenone + Fenpiverinium + Benzyl Alcohol" },
  { id: 250, combination: "Nimesulide + Serratiopeptidase" },
  { id: 251, combination: "Nimesulide + Tizanidine" },
  { id: 252, combination: "Nimorazole + Ofloxacin" },
  { id: 253, combination: "Norfloxacin+ Metronidazole + Zinc Acetate" },
  { id: 254, combination: "Oflaxacin + Ornidazole Suspension" },
  { id: 255, combination: "Ofloxacin + Clotrimazole + Betamethasone + Lignocaine" },
  { id: 256, combination: "Ofloxacin + Metronidazole + Zinc Acetate" },
  { id: 257, combination: "Ofloxacin + Nitazoxanide" },
  { id: 258, combination: "Ofloxacin + Ornidazole + Zinc Bisglycinate" },
  { id: 259, combination: "Olmesartan + Hydrochlorothiazide + Chlorthalidone" },
  { id: 260, combination: "Omepraozle + Paracetmaol+ Diclofenac" },
  { id: 261, combination: "Oxetacaine + Magaldrate + Famotidine" },
  { id: 262, combination: "Pantoprazole (as Enteric Coated Tablet) + Zinc Carnosine (as Film Coated Tablets" },
  { id: 263, combination: "Paracetamol + Ambroxol + Phenylephrine + Chlorpheniramine" },
  { id: 264, combination: "Paracetamol + Caffeine + Codeine" },
  { id: 265, combination: "Paracetamol + Caffine + Phenylephrine + Chlorpheniramine" },
  { id: 266, combination: "Paracetamol + Cetrizine + Caffeine" },
  { id: 267, combination: "Paracetamol + Chlorpheniramine + Ambroxol + Guaifenesin + Phenylephrine" },
  { id: 268, combination: "Paracetamol + Codeine + Chlorpheniramine" },
  { id: 269, combination: "Paracetamol + Dextromethorphan + Bromhexine + Phenylephrine + Diphenhydramine" },
  { id: 270, combination: "Paracetamol + Dextromethorphan + Chlorpheniramine" },
  { id: 271, combination: "Paracetamol + Diclofenac + famotidine" },
  { id: 272, combination: "Paracetamol + Disodium Hydrogen Citrate + Caffeine" },
  { id: 273, combination: "Paracetamol + DL Methionine" },
  { id: 274, combination: "Paracetamol + domperidone + Caffeine" },
  { id: 275, combination: "Paracetamol + Levocetirizine + Phenylephirine + Zink Gluconate" },
  { id: 276, combination: "Paracetamol + Levocetirizine + Pseudoephedrine" },
  { id: 277, combination: "Paracetamol + Loratadine + Dextromethophan + Pseudoepheridine + Caffeine" },
  { id: 278, combination: "Paracetamol + Loratadine + Phenylephrine + Dextromethorphan + Caffeine" },
  { id: 279, combination: "Paracetamol + mefenamic Acid + ranitidine + Dicyclomine" },
  { id: 280, combination: "Paracetamol + Pheniramine" },
  { id: 281, combination: "Paracetamol + Phenylephrine + Chlorpheneramine + Dextromethorphan + caffeine" },
  { id: 282, combination: "Paracetamol + Phenylephrine + Chlorpheniramine + Zinc Gluconate" },
  { id: 283, combination: "Paracetamol + Phenylephrine + Desloratadine + Zinc Gluconate + Ambroxol" },
  { id: 284, combination: "Paracetamol + Phenylephrine + Levocetirizine + Caffeine" },
  { id: 285, combination: "Paracetamol + Phenylephrine + Triprolidine" },
  { id: 286, combination: "Paracetamol + Phenylephrine + Triprolidine + Caffeine" },
  { id: 287, combination: "Paracetamol + Prochloperazine" },
  { id: 288, combination: "Paracetamol + Prochlorperazine Maleate" },
  { id: 289, combination: "Paracetamol + Promethazine" },
  { id: 290, combination: "Paracetamol + Propyphenazone + Caffeine" },
  { id: 291, combination: "Paracetamol + Pseudoephedrine + Cetrizine" },
  { id: 292, combination: "Paracetamol + Pseudoephedrine + Dextromethorphan + Cetirizine" },
  { id: 293, combination: "Paracetamol + Tapentadol" },
  { id: 294, combination: "Paracetamol+Phenylephrine+Levocetirizine+Sodium Citrate" },
  { id: 295, combination: "Paracetamol+Pseudoephedrine+Certirizine+Caffeine" },
  { id: 296, combination: "Permethrin + Cetrimide + Menthol" },
  { id: 297, combination: "phenylbutazone + sodium salicylate" },
  { id: 298, combination: "Phenylephrine + Chlorpheniramine + Paracetamol + Bromhexine + Caffeine" },
  { id: 299, combination: "Pholcodine + Phenylephrine + Promethazine" },
  { id: 300, combination: "Pioglitazone 15mg + Metformin 850 mg" },
  { id: 301, combination: "Pioglitazone 30 mg + Metformin 500 mg" },
  { id: 302, combination: "Pioglitazone 7.5/7.5mg + Metformin 500/1000mg" },
  { id: 303, combination: "Pseudoephedrine + Bromhexine" },
  { id: 304, combination: "Pseudoephedrine + Cetirizine" },
  { id: 305, combination: "Pseudoephedrine + Dextromethorphan + Cetirizine" },
  { id: 306, combination: "Rabeprazole + Diclofenac + Paracetamol" },
  { id: 307, combination: "Rabeprazole + Zinc + Domperidone" },
  { id: 308, combination: "Rabeprazole + Zinc Carnosine" },
  { id: 309, combination: "Ranitidine + Domperidone + Simethicone" },
  { id: 310, combination: "Ranitidine + Magaldrate" },
  { id: 311, combination: "Ranitidine + Magaldrate + Simethicone" },
  { id: 312, combination: "Roxithromycin + Serratiopeptidase" },
  { id: 313, combination: "Salbutamol + Aminophylline + Guaiphensin" },
  { id: 314, combination: "Salbutamol + Bromhexine + Guaiphenesin + Menthol" },
  { id: 315, combination: "Salbutamol + Certirizine + Ambroxol" },
  { id: 316, combination: "Salbutamol + Choline Theophylinate + Ambroxol" },
  { id: 317, combination: "Salbutamol + Choline Theophylinate + Carbocisteine" },
  { id: 318, combination: "Salbutamol + Theophylline + Bromhexine" },
  { id: 319, combination: "Salbutamol+Hydroxyethyltheophylline (Etofylline) + Bromhexine" },
  { id: 320, combination: "Sildenafil + Estradiol Valerate" },
  { id: 321, combination: "Tamsulosin + Diclofenac" },
  { id: 322, combination: "Telmisartan + Metformin" },
  { id: 323, combination: "Terbutaline + Ambroxol + Guaiphenesin + Zinc + Menthol" },
  { id: 324, combination: "Terbutaline + Bromhexine + Etofylline" },
  { id: 325, combination: "Terbutaline + Bromhexine + Guaiphenesin + Dextromethorphan" },
  { id: 326, combination: "Terbutaline + Etofylline + Ambroxol" },
  { id: 327, combination: "Terbutaline + N-Acetyl L-Cysteine + Guaifenesin" },
  { id: 328, combination: "Terpinhydrate + Dextromethorphan + Menthol" },
  { id: 329, combination: "Thyroid + Thiamine + Riboflavin + Phyridoxine + Calcium Pantothenate + Tocopheryl Acetate +Nicotinamide" },
  { id: 330, combination: "Thyroxine + Pyridoxine + Folic Acid" },
  { id: 331, combination: "Tranexamic Acid + Proanthocyanidin" },
  { id: 332, combination: "Ursodeoxycholic Acid + Silymarin" },
  { id: 333, combination: "Voglibose + Pioglitazone + Metformin" },
  { id: 334, combination: "Voglibose+ Metformin + Chromium Picolinate" },
  { id: 335, combination: "Zinc Carnosine + Magnesium Hydroxide + Dried Aluminium Hydroxide + Simethicone" },
  { id: 336, combination: "Zinc Carnosine + Oxetacaine" },
  { id: 337, combination: "Zinc Carnosine + Sucralfate" },
  { id: 338, combination: "Artesunate + Arteether + Artemether" },
  { id: 339, combination: "Cyproheptadine (2mg & 4mg) in Combination with Multivitamin" },
  { id: 340, combination: "Halofantrine" },
  { id: 341, combination: "Multi-Dose Anti-Malaria Oral Suspensions" },
  { id: 342, combination: "Ketoconazole Tablet" },
  { id: 343, combination: "Diclofenac Sodium 50mg + Paracetamol 325mg + Chlorzoxazone 250mg" },
  { id: 344, combination: "Diclofenac Potassium 100mg" },
  { id: 345, combination: "Chloroquine Injection" },
  { id: 346, combination: "Analgin (Metamizole) / Novalgin (Dipyrone)" },
  { id: 347, combination: "Aceclofenac Sodium 100mg + Paracetamol 500mg + Chlorzoxazone 250mg" },
  { id: 348, combination: "Dichlorvos (DDVP) ≤100ml pack sizes" },
  { id: 349, combination: "Antibiotics as Growth Promoters in Livestock" },
  { id: 350, combination: "Banned Veterinary Pharmaceuticals in Food-Producing Animals" },
  { id: 351, combination: "Colistin as Coccidiostat" },
  { id: 352, combination: "Ethoxyquin in Feed for Food-Producing Animals" },
  { id: 353, combination: "Paraquat" }
];