// Official NAFDAC Dossier Screening Checklist

import { checkCeilingList } from './nafdacCeilingList.js';
import { checkFivePlusFivePolicy } from './fivePlusFivePolicy.js';
import { checkImportProhibitionList } from './importProhibitionList.js';

export const INTERNAL_SCREENING_CHECKLIST = [
  {
    id: 1,
    section: "DMS Portal Verification",
    question: "Confirm that the dossier attached to the application is what is stated on the DMS portal?",
    guide: "The dossier attached to the application is confirmed in Module 1, section 3.2.P.1, 3.2.P.3.1 to be the same as that stated on the DMS Portal. Please confirm Product name, Manufacturer's Name & Address on DMS is the same as that in Dossier Attached.",
    moduleRef: "Module 1 / 3.2.P.1 / 3.2.P.3.1",
  },
  {
    id: 2,
    section: "Regulatory Compliance",
    question: "Is the product on the NAFDAC ceiling list or on the Federal Government Import Prohibition List (Imported products only)?",
    guide: "Please check the following: NAFDAC Ceiling list (36 prohibited products), Federal Government Import Prohibition List, 5+5 Policy. Products on ceiling list cannot be registered.",
    moduleRef: "Module 1.3.1",
    checkCeilingList: true,
    checkFivePlusFive: true,
    checkImportProhibition: true,
    autoExtractProduct: true,
  },
  {
    id: 3,
    section: "Regulatory Compliance",
    question: "Is the product on the list of Regulatory Directive on Discontinuation of Registration of some Fixed Dose Combinations (FDC) or affected by other regulatory directives?",
    guide: "Check Regulatory Directive on Discontinuation of Registration of some FDCs and other Regulatory Directives.",
    moduleRef: "General / Pre-screening",
    checkRegulatoryDirective: true,
  },
  {
    id: 4,
    section: "API Compliance",
    question: "Is the API from one of the approved sources or Does the API have a satisfactory test result from an accredited laboratory?",
    guide: "Verify API is from approved sources. Check for Certificate of suitability to the European Pharmacopoeia (CEP) in Module 1.2.15. API certified by accredited quality control laboratory in Module 1. Certificate of analysis from ISO 17025:2017 accredited laboratory in 3.2.S.4.4.",
    moduleRef: "Module 1.2.15 / 3.2.S.4.4",
  },
  {
    id: 5,
    section: "Product Information",
    question: "Is the SmPC provided in the product dossier?",
    guide: "The SmPC is provided in the product dossier in module 1, section 1.3.1.",
    moduleRef: "Module 1.3.1",
  },
  {
    id: 6,
    section: "Dossier Completeness",
    question: "Is the general checklist complete? Are all required documents present in the dossier?",
    guide: "Run the general checklist to verify all required documents are present. Check document compliance rate and ensure critical documents are not missing.",
    moduleRef: "General Checklist",
    checkGeneralChecklist: true,
  },
  {
    id: 7,
    section: "Quality Documents",
    question: "Has the applicant submitted the Quality Overall Summary – Product Dossier (QOS-PD) and Quality Information Summary (QIS) as Word documents and in line with the NAFDAC template?",
    guide: "Please confirm in section 2.3 (QOS) and 1.4.2 (QIS) respectively. Also can be found in section for 'Other files' on the DMS platform.",
    moduleRef: "Module 2.3 / 1.4.2",
  },
  {
    id: 8,
    section: "Product Specifications",
    question: "Is there an acceptable specification in the dossier (i.e., signed, dated, and version-controlled)?",
    guide: "Please confirm FPP specification is provided, signed, dated and version-controlled. FPP specification should be provided in Module 3 under section 3.2.P.5.1 of the product dossier.",
    moduleRef: "Module 3.2.P.5.1",
  },
  {
    id: 9,
    section: "Bioequivalence/Biowaiver",
    question: "Is data on BE or BW provided in module 5? If yes, is BTIF or BAF in word format provided in module 1 or 2?",
    guide: "For Solid orals (Tablets or Capsules): Check if Data on BE and BW provided or Not.",
    moduleRef: "Module 5 / Module 1-2",
  },
  {
    id: 10,
    section: "Narrow Therapeutic Index",
    question: "Does the product (or for an FDC any of the Actives) have a Narrow Therapeutic Index?",
    guide: "Please check List of Narrow Therapeutic Index shared. BE is Mandatory for such products.",
    moduleRef: "General / Pre-screening",
    checkNTI: true,
  },
  {
    id: 11,
    section: "Batch Consistency",
    question: "Are the submission batches in the dossier consistent, and at minimum two batches of pilot scale? (2.3.P.2.2.1, 3.2.P.5.4, and 3.2.P.8.3, R.1.1)",
    guide: "Please confirm batches are consistent across sections 3.2.P.5.4 (Batch Analysis), 3.2.P.8.3 (Stability data), and 3.2.R.1.1 (Executed BMR). The submission batches should be consistent.",
    moduleRef: "Module 3.2.P.2.2.1 / 3.2.P.5.4 / 3.2.P.8.3 / 3.2.R.1.1",
  },
  {
    id: 12,
    section: "Batch Manufacturing Records",
    question: "Is the executed BMR for the bio batch (or representative batch/CPD batch) provided in 3.2.R.1.1 as well as the proposed blank BMR(s) in R.1.2?",
    guide: "Please confirm Executed BMR provided with Batch Number, Batch size, Product name/Active Ingredients, Manufacturer. Check if executed BMR for bio batch provided and Proposed Blank/Master BMR provided. Also can be found in 'Other files' on DMS platform.",
    moduleRef: "Module 3.2.R.1.1 / 3.2.R.1.2",
  },
  {
    id: 13,
    section: "Batch Manufacturing Records",
    question: "Confirm if the blank BMR is provided for all the proposed batch sizes and whether the BMR(s) is/are text selectable or bookmarked, includes the name of the product and the batch formula?",
    guide: "Please confirm Master/Blank BMR provided for proposed batch sizes, Name of the product/Active Ingredients, Batch formula, Manufacturer, Text selectable or bookmarked. Also can be found in 'Other files' on DMS platform.",
    moduleRef: "Module 3.2.R.1.2",
  },
  {
    id: 14,
    section: "Dissolution Profile",
    question: "Has the applicant provided data on the comparative dissolution profile using the batch provided in 3.2.R.1.1 against the innovator or any other reference listed product? Confirm this from 3.2.P.2 and/or in module 5",
    guide: "Please confirm Data on comparative dissolution profile was provided in section 3.2.P.2 or section 5.3.1.2. In the three BCS class media (0.1N HCL, ph 4.5 Acetate buffer, pH 6.8 Phosphate buffer). For 12-units of tablet at Multipoints (10, 20, & 30 minutes). Please note that CDP is not applicable for Solutions/Most Injectables.",
    moduleRef: "Module 3.2.P.2 / 5.3.1.2",
  },
  {
    id: 15,
    section: "Stability Data",
    question: "Has the applicant provided six (6) months accelerated stability data and at least twelve (12) months long-term stability data for at least two pilot scale batches of the FPP at Zone IVB Climatic conditions (30±2°C and 75±5%RH) in 3.2.P.8.3?",
    guide: "Check stability study at accelerated condition (40ºC±2ºC,75%±5%RH) for 6 months and at long-term conditions (30ºC ±2ºC,75%±5%RH) for at least 12 months for at least two pilot scale batches.",
    moduleRef: "Module 3.2.P.8.3",
  },
  {
    id: 16,
    section: "Sterilization Method",
    question: "Confirm the method of sterilization used for the product.",
    guide: "Only for Sterile products: Check Dry Heat and Moist heat Sterilization or Aseptic Sterilization. Please check in the Process Validation Report for Method of Sterilization.",
    moduleRef: "Process Validation Report",
    conditionalFor: "sterile products",
  },
  {
    id: 20,
    section: "Process Validation",
    question: "Is there process validation report for three consecutive batches?",
    guide: "Please confirm Process Validation Reports for three consecutive batches with Batch Size provided.",
    moduleRef: "Process Validation Report",
  },
];